/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as EncoreEngineRouteImport } from './routes/encore-engine'
import { Route as Encore_engineRouteImport } from './routes/encore_engine'
import { Route as ExchangeRouteImport } from './routes/exchange'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as How_it_worksRouteImport } from './routes/how_it_works'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as MaterialsRouteImport } from './routes/materials'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as DashboardAdminRouteImport } from './routes/dashboard.admin'
import { Route as DashboardBuyerRouteImport } from './routes/dashboard.buyer'
import { Route as DashboardSellerRouteImport } from './routes/dashboard.seller'
import { Route as ListingIdRouteImport } from './routes/listing.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const EncoreEngineRoute = EncoreEngineRouteImport.update({
  id: '/encore-engine',
  path: '/encore-engine',
  getParentRoute: () => rootRouteImport,
} as any)
const Encore_engineRoute = Encore_engineRouteImport.update({
  id: '/encore_engine',
  path: '/encore_engine',
  getParentRoute: () => rootRouteImport,
} as any)
const ExchangeRoute = ExchangeRouteImport.update({
  id: '/exchange',
  path: '/exchange',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const How_it_worksRoute = How_it_worksRouteImport.update({
  id: '/how_it_works',
  path: '/how_it_works',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const MaterialsRoute = MaterialsRouteImport.update({
  id: '/materials',
  path: '/materials',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAdminRoute = DashboardAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBuyerRoute = DashboardBuyerRouteImport.update({
  id: '/buyer',
  path: '/buyer',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSellerRoute = DashboardSellerRouteImport.update({
  id: '/seller',
  path: '/seller',
  getParentRoute: () => DashboardRoute,
} as any)
const ListingIdRoute = ListingIdRouteImport.update({
  id: '/listing/$id',
  path: '/listing/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/encore-engine': typeof EncoreEngineRoute
  '/encore_engine': typeof Encore_engineRoute
  '/exchange': typeof ExchangeRoute
  '/faq': typeof FaqRoute
  '/how-it-works': typeof HowItWorksRoute
  '/how_it_works': typeof How_it_worksRoute
  '/login': typeof LoginRoute
  '/marketplace': typeof MarketplaceRoute
  '/materials': typeof MaterialsRoute
  '/pricing': typeof PricingRoute
  '/register': typeof RegisterRoute
  '/resources': typeof ResourcesRoute
  '/security': typeof SecurityRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/buyer': typeof DashboardBuyerRoute
  '/dashboard/seller': typeof DashboardSellerRoute
  '/listing/$id': typeof ListingIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/encore-engine': typeof EncoreEngineRoute
  '/encore_engine': typeof Encore_engineRoute
  '/exchange': typeof ExchangeRoute
  '/faq': typeof FaqRoute
  '/how-it-works': typeof HowItWorksRoute
  '/how_it_works': typeof How_it_worksRoute
  '/login': typeof LoginRoute
  '/marketplace': typeof MarketplaceRoute
  '/materials': typeof MaterialsRoute
  '/pricing': typeof PricingRoute
  '/register': typeof RegisterRoute
  '/resources': typeof ResourcesRoute
  '/security': typeof SecurityRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/buyer': typeof DashboardBuyerRoute
  '/dashboard/seller': typeof DashboardSellerRoute
  '/listing/$id': typeof ListingIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/encore-engine': typeof EncoreEngineRoute
  '/encore_engine': typeof Encore_engineRoute
  '/exchange': typeof ExchangeRoute
  '/faq': typeof FaqRoute
  '/how-it-works': typeof HowItWorksRoute
  '/how_it_works': typeof How_it_worksRoute
  '/login': typeof LoginRoute
  '/marketplace': typeof MarketplaceRoute
  '/materials': typeof MaterialsRoute
  '/pricing': typeof PricingRoute
  '/register': typeof RegisterRoute
  '/resources': typeof ResourcesRoute
  '/security': typeof SecurityRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/buyer': typeof DashboardBuyerRoute
  '/dashboard/seller': typeof DashboardSellerRoute
  '/listing/$id': typeof ListingIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/dashboard'
    | '/encore-engine'
    | '/encore_engine'
    | '/exchange'
    | '/faq'
    | '/how-it-works'
    | '/how_it_works'
    | '/login'
    | '/marketplace'
    | '/materials'
    | '/pricing'
    | '/register'
    | '/resources'
    | '/security'
    | '/sitemap.xml'
    | '/dashboard/admin'
    | '/dashboard/buyer'
    | '/dashboard/seller'
    | '/listing/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/dashboard'
    | '/encore-engine'
    | '/encore_engine'
    | '/exchange'
    | '/faq'
    | '/how-it-works'
    | '/how_it_works'
    | '/login'
    | '/marketplace'
    | '/materials'
    | '/pricing'
    | '/register'
    | '/resources'
    | '/security'
    | '/sitemap.xml'
    | '/dashboard/admin'
    | '/dashboard/buyer'
    | '/dashboard/seller'
    | '/listing/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/dashboard'
    | '/encore-engine'
    | '/encore_engine'
    | '/exchange'
    | '/faq'
    | '/how-it-works'
    | '/how_it_works'
    | '/login'
    | '/marketplace'
    | '/materials'
    | '/pricing'
    | '/register'
    | '/resources'
    | '/security'
    | '/sitemap.xml'
    | '/dashboard/admin'
    | '/dashboard/buyer'
    | '/dashboard/seller'
    | '/listing/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  EncoreEngineRoute: typeof EncoreEngineRoute
  Encore_engineRoute: typeof Encore_engineRoute
  ExchangeRoute: typeof ExchangeRoute
  FaqRoute: typeof FaqRoute
  HowItWorksRoute: typeof HowItWorksRoute
  How_it_worksRoute: typeof How_it_worksRoute
  LoginRoute: typeof LoginRoute
  MarketplaceRoute: typeof MarketplaceRoute
  MaterialsRoute: typeof MaterialsRoute
  PricingRoute: typeof PricingRoute
  RegisterRoute: typeof RegisterRoute
  ResourcesRoute: typeof ResourcesRoute
  SecurityRoute: typeof SecurityRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ListingIdRoute: typeof ListingIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/encore-engine': {
      id: '/encore-engine'
      path: '/encore-engine'
      fullPath: '/encore-engine'
      preLoaderRoute: typeof EncoreEngineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/encore_engine': {
      id: '/encore_engine'
      path: '/encore_engine'
      fullPath: '/encore_engine'
      preLoaderRoute: typeof Encore_engineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exchange': {
      id: '/exchange'
      path: '/exchange'
      fullPath: '/exchange'
      preLoaderRoute: typeof ExchangeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how_it_works': {
      id: '/how_it_works'
      path: '/how_it_works'
      fullPath: '/how_it_works'
      preLoaderRoute: typeof How_it_worksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/materials': {
      id: '/materials'
      path: '/materials'
      fullPath: '/materials'
      preLoaderRoute: typeof MaterialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/admin': {
      id: '/dashboard/admin'
      path: '/admin'
      fullPath: '/dashboard/admin'
      preLoaderRoute: typeof DashboardAdminRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/buyer': {
      id: '/dashboard/buyer'
      path: '/buyer'
      fullPath: '/dashboard/buyer'
      preLoaderRoute: typeof DashboardBuyerRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/seller': {
      id: '/dashboard/seller'
      path: '/seller'
      fullPath: '/dashboard/seller'
      preLoaderRoute: typeof DashboardSellerRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/listing/$id': {
      id: '/listing/$id'
      path: '/listing/$id'
      fullPath: '/listing/$id'
      preLoaderRoute: typeof ListingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteChildren {
  DashboardAdminRoute: typeof DashboardAdminRoute
  DashboardBuyerRoute: typeof DashboardBuyerRoute
  DashboardSellerRoute: typeof DashboardSellerRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAdminRoute: DashboardAdminRoute,
  DashboardBuyerRoute: DashboardBuyerRoute,
  DashboardSellerRoute: DashboardSellerRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRouteWithChildren,
  EncoreEngineRoute: EncoreEngineRoute,
  Encore_engineRoute: Encore_engineRoute,
  ExchangeRoute: ExchangeRoute,
  FaqRoute: FaqRoute,
  HowItWorksRoute: HowItWorksRoute,
  How_it_worksRoute: How_it_worksRoute,
  LoginRoute: LoginRoute,
  MarketplaceRoute: MarketplaceRoute,
  MaterialsRoute: MaterialsRoute,
  PricingRoute: PricingRoute,
  RegisterRoute: RegisterRoute,
  ResourcesRoute: ResourcesRoute,
  SecurityRoute: SecurityRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ListingIdRoute: ListingIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
